logeique2/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spaces.urls', namespace='spaces')),
    path('search/', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search, name='search')
]

spaces/urls.py
from django.urls import path
from . import views

app_name = "spaces"

urlpatterns = [
    path('', views.home, name="home"),
    path('signup', views.sign_up, name="signup"),
    path('signin/', views.sign_in, name="signin"),
    path('logout/', views.log_out, name="logout"),
    path('client/profile/<int:id>',
         views.see_profile, name="see_client_profile"),
    path('landlord/profile/<int:id>',
         views.see_profile, name="see_landlord_profile"),
    path('user/edit/profile/<int:id>', views.edit_profile, name="edit_profile"),
    path('add/house/<int:id>', views.add_house, name="add_house"),
    path('see/house/<int:id>' , views.see_houses , name="see_houses")

]

spaces/forms.py
from django import forms


class SignUpForm(forms.Form):
    username = forms.CharField(label='Pseudo : ', max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control inbox', 'title': 'Pseudo', 'placeholder': 'Entrez votre pseudo'}))
    first_name = forms.CharField(label='Prenom : ', max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control inbox', 'title': 'Prenom', 'placeholder': 'Entrez votre Prenom'}))
    last_name = forms.CharField(label='Nom', max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control inbox', 'title': 'Nom', 'placeholder': 'Entrez votre Nom'}))
    email = forms.EmailField(label='Email : ', required=False, widget=forms.EmailInput(
        attrs={'class': 'form-control inbox', 'title': 'Email', 'placeholder': 'Entrez votre addresse electronique', 'id': 'lo_em'}))
    contact = forms.CharField(label='Contact : ', widget=forms.TextInput(
        attrs={'class': 'form-control inbox', 'title': 'Contact', 'placeholder': 'Exemple : 00-00-00-00', 'id': 'lo_nu'}))
    client = forms.BooleanField(label='Client : ', required=False, widget=forms.CheckboxInput(
        attrs={'class': 'form-check-input stick', 'onclick': 'active()', 'id': 'is_cl'}))
    landlord = forms.BooleanField(label='Proprietaire : ', required=False, widget=forms.CheckboxInput(
        attrs={'class': 'form-check-input stick', 'onclick': 'active()', 'id': 'is_la'}))
    password = forms.CharField(label='Mot de passe :', max_length=200, widget=forms.PasswordInput(attrs={
        'class': 'form-control inbox', 'title': 'Mot de passe', 'placeholder': 'Entrez votre mot de passe'}))
    password_verification = forms.CharField(label='Vérification', max_length=200, widget=forms.PasswordInput(attrs={
        'class': 'form-control inbox', 'title': 'Vérification', 'placeholder': 'Entrez votre mot de passe à nouveau'}))


class SignInForm(SignUpForm):
    first_name = None
    last_name = None
    email = None
    contact = None
    password_verification = None


class EditForm(forms.Form):
    username = forms.CharField(label='Pseudo : ', max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control inbox', 'title': 'Pseudo', 'placeholder': 'Entrez votre pseudo'}))
    first_name = forms.CharField(label='Prenom : ', max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control inbox', 'title': 'Prenom', 'placeholder': 'Entrez votre Prenom'}))
    last_name = forms.CharField(label='Nom', max_length=200, required=False, widget=forms.TextInput(attrs={
        'class': 'form-control inbox', 'title': 'Nom', 'placeholder': 'Entrez votre Nom'}))
    email = forms.EmailField(label='Email : ', required=False, widget=forms.EmailInput(attrs={
                             'class': 'form-control inbox', 'title': 'Email', 'placeholder': 'Entrez votre addresse electronique', 'id': 'lo_em'}))
    contact = forms.CharField(label='Contact : ', required=False, widget=forms.TextInput(
        attrs={'class': 'form-control inbox', 'title': 'Contact', 'placeholder': 'Exemple : + 225 00-00-00-00', 'id': 'lo_nu'}))
    password = forms.CharField(label='Mot de passe :', required=False,  max_length=200, widget=forms.PasswordInput(
        attrs={'class': 'form-control inbox', 'title': 'Mot de passe', 'placeholder': 'Entrez votre mot de passe'}))
    password_verification = forms.CharField(label='Vérification', required=False, max_length=200, widget=forms.PasswordInput(
        attrs={'class': 'form-control inbox', 'title': 'Vérification', 'placeholder': 'Entrez votre mot de passe à nouveau'}))
    rent_proposal = forms.IntegerField(label='budget loyer', required=False)
    deposit_proposal = forms.IntegerField(
        label='budget caution', required=False)
    avatar = forms.ImageField(label='ajoute avatar', required=False)


class AddHouseForm(forms.Form):
    house_township = forms.CharField(max_length=50, label='Commune')
    house_area = forms.CharField(max_length=50, label='Quartier')
    house_rent = forms.IntegerField(label='Loyer')
    house_deposit = forms.IntegerField(label='Caution')
    house_kind = forms.CharField(max_length=50, label='Type de maison')
    house_rooms_number = forms.IntegerField(label='Nombres de pieces')
    house_available = forms.BooleanField(label='disponible', required=False)
    house_to_sell = forms.BooleanField(label='A vendre', required=False)
    house_image = forms.ImageField(label='Image', required=False)

spaces/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import SignUpForm, SignInForm, EditForm, AddHouseForm
from django.contrib.auth.models import User
from .models import Client, Landlord, House
from django.shortcuts import get_object_or_404, Http404
from django.contrib.auth.decorators import login_required
from spaces.models import Client, Landlord
import re
import os
from PIL import Image 
from search.forms import SearchForm

houses_path= os.path.abspath("C:/Users/XC-DEV-3/Documents/projet soutenance/logeique2/media/img/houses")
avatars_path = os.path.abspath("C:/Users/XC-DEV-3/Documents/projet soutenance/logeique2/media/img/avatars")

max_height= 540
max_width= 304
extensions= ['PNG','JPG']

def adjusted_size(width,height):
    if width>max_width or height>max_height:
        if width>height:
            return max_width, int (max_width * height/ width)
        else:
            return int (max_height*width/height), max_height
    else:
        return width,height

  
def resize(path , f): 
    try:
        if f in os.listdir(path):
            if os.path.isfile(os.path.join(path,f)):
                f_text, f_ext= os.path.splitext(f)
                f_ext= f_ext[1:].upper()
                if f_ext in extensions:
                    image = Image.open(os.path.join(path,f))
                    width, height= image.size
                    image = image.resize(adjusted_size(width , height))
                    return f
    except IOError: 
        pass

def is_valid_contact(number):
    contact_valid = False
    phoneRegex = re.compile(r'''(
        (\+?\d{1,3}|\+?\(\d{1,3}\))?#Area code
        (\s|-)? #separator 
        \d{2} #Deux premiers chiffres
        (-) #separator
        \d{2} #Deux deuxiemes
        (-) #separator
        \d{2}
        (-) #separator
        \d{2}
        )''', re.VERBOSE
                            )

    mo = phoneRegex.search(number)
    if mo == None:
        contact_valid = False
    else:
        contact_valid = True
    return contact_valid

# Create your views here.


def home(request):
    form = SearchForm()
    return render(request, 'spaces/index.html', locals())


def sign_up(request):
    form = SignUpForm()
    users = User.objects.all()
    clients = Client.objects.all()
    landlords = Landlord.objects.all()
    email_unique_error = False
    pass_different_err = False
    contact_exist_error = False
    invalid_contact_err = False

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            contact = form.cleaned_data['contact']
            client = form.cleaned_data['client']
            landlord = form.cleaned_data['landlord']
            password1 = form.cleaned_data['password']
            password2 = form.cleaned_data['password_verification']

            if is_valid_contact(contact) == False:
                invalid_contact_err = True
                return render(request, 'spaces/signup.html', locals())

            if password1 == password2:
                if client:
                    if email:
                        for each_user in users:
                            each_user.email = each_user.email.lower()
                            email = email.lower()
                            if each_user.email == email:
                                email_unique_error = True
                                return render(request, 'spaces/signup.html', locals())

                        for each_client in clients:
                            each_client.contact = each_client.contact.split(
                                '-')
                            each_client.contact = "".join(each_client.contact)
                            contact_mo = contact.split('-')
                            contact_mo = "".join(contact)
                            if each_client.contact == contact_mo:
                                contact_exist_error = True
                                return render(request, 'spaces/signup.html', locals())
                        user = User.objects.create_user(
                            username=username, first_name=first_name, last_name=last_name, email=email, password=password1)
                        user.save()
                        client = Client(user=user, contact=contact)
                        client.save()

                    elif not email:
                        for each_client in clients:
                            each_client.contact = each_client.contact.split(
                                '-')
                            each_client.contact = "".join(each_client.contact)
                            contact_mo = contact.split('-')
                            contact_mo = "".join(contact)
                            if each_client.contact == contact_mo:
                                contact_exist_error = True
                                return render(request, 'spaces/signup.html', locals())
                        user = User.objects.create_user(
                            username=username, first_name=first_name, last_name=last_name, password=password1)
                        user.save()
                        client = Client(user=user, contact=contact)
                        client.save()

                elif landlord:
                    if email:
                        for each_user in users:
                            each_user.email = each_user.email.lower()
                            email = email.lower()
                            if each_user.email == email:
                                email_unique_error = True
                                return render(request, 'spaces/signup.html', locals())
                        for each_landlord in landlords:
                            each_landlord.contact = each_landlord.contact.split(
                                '-')
                            each_landlord.contact = "".join(
                                each_landlord.contact)
                            contact_mo = contact.split('-')
                            contact_mo = "".join(contact)
                            if each_landlord.contact == contact_mo:
                                contact_exist_error = True
                                return render(request, 'spaces/signup.html', locals())
                        user = User.objects.create_user(
                            username=username, first_name=first_name, last_name=last_name, email=email, password=password1)
                        user.save()
                        landlord = Landlord(user=user, contact=contact)
                        landlord.save()
                    elif not email:
                        for each_landlord in landlords:
                            each_landlord.contact = each_landlord.contact.split(
                                '-')
                            each_landlord.contact = "".join(
                                each_landlord.contact)
                            contact_mo = contact.split('-')
                            contact_mo = "".join(contact)
                            if each_landlord.contact == contact_mo:
                                contact_exist_error = True
                                return render(request, 'spaces/signup.html', locals())
                        user = User.objects.create_user(
                            username=username, first_name=first_name, last_name=last_name, password=password1)
                        landlord = Landlord(user=user, contact=contact)
                        landlord.save()

            elif password1 != password2:
                pass_different_err = True
                return render(request, 'spaces/signup.html', locals())
            return render(request, 'spaces/signin.html', locals())

    context = {'form': form}
    return render(request, 'spaces/signup.html', locals())


def sign_in(request):
    form = SignInForm()
    error = False
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            client_check = form.cleaned_data['client']
            landlord_check = form.cleaned_data['landlord']
            if client_check:
                try:
                    user_tempt = get_object_or_404(User, username=username)
                    client_user = get_object_or_404(
                        Client, user_id=user_tempt.id)
                    if client_user:
                        client_user = authenticate(
                            username=username, password=password)

                        if client_user:
                            login(request, client_user)

                        else:
                            error = True
                except Http404:
                    user_tempt = None
                    error = True

            elif landlord_check:
                try:
                    user_tempt = get_object_or_404(User, username=username)
                    landlord_user = get_object_or_404(
                        Landlord, user_id=user_tempt.id)
                    if landlord_user:
                        landlord_user = authenticate(
                            username=username, password=password)

                        if landlord_user:
                            login(request, landlord_user)
                        else:
                            error = True
                except Http404:
                    user_tempt = None
                    error = True

    return render(request, 'spaces/signin.html', locals())


@login_required()

spaces/templates/spaces/index.html
{% extends 'spaces/base.html' %}
{% block title %}Acceuil{% endblock %}

spaces/templates/spaces/see_houses.html
{% if no_house_err %}
<p>Vous n'avez aucune maisons pour l'instant</p>
{% endif %}
{% for house in houses %}
    {% if house.house_image %}
    <div>
        <img src="{{house.house_image.url}}" alt="image de maison">
        <p>Commune: {{house.house_township}} {{area}}</p>
        <p>Loyer: {{house.house_rent}} FCFA</p>
        <p>Caution: {{house.house_deposit}} FCFA</p>
        <p>Type: {{house.house_kind}}</p>
        <p>{{house.house_rooms_number}} pieces</p>
        {% if house.house_available %}
            <P>Disponible</P>
        {% else %}
        <p>Indisponible</p>
        {% endif %}
    </div>
    {% endif %}
{% endfor %}

spaces/templates/spaces/see_landlord_profile.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Dashboard Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/dashboard/">
    <link rel="stylesheet"
        href="C:/Users/deoth/Downloads/Compressed/bootstrap-4.3.1-dist/bootstrap-4.3.1-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    {% load static %}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">{{user.username}}</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse"
            data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="{% url 'spaces:logout' %}">Se deconnecter</a>
            </li>
        </ul>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <span data-feather="home"></span>{{user.username}}
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                            {% if user.landlord.avatar %}
                                <img src="{{user.landlord.avatar.url}}" alt="Image de {{user.username}}">
                            {% endif %}
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'spaces:edit_profile' user.id %}">
                                <span data-feather="user"></span>
                                Profil
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'spaces:add_house' user.id %}">
                                <span data-feather="plus"></span>
                                Ajouter Maisons
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'spaces:see_houses' user.id %}">
                                <span data-feather="home"></span>
                                Voir ses Maisons
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="users"></span>
                                Clients
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bar-chart-2"></span>
                                Statistiques
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="bell"></span>
                                Notifications
                            </a>
                        </li>
                    </ul>

                    <h6
                        class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Statistiques enregistrées</span>
                        <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Ce mois
                            </a>
                        </li>

                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                <div
                    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Dashboard</h1>
                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group mr-2">
                            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                            <span data-feather="calendar"></span>
                            This week
                        </button>
                    </div>
                </div>

                <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>

                <h2>Section title</h2>
                <div class="table-responsive">
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Header</th>
                                <th>Header</th>
                                <th>Header</th>
                                <th>Header</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1,001</td>
                                <td>Lorem</td>
                                <td>ipsum</td>
                                <td>dolor</td>
                                <td>sit</td>
                            </tr>
                            <tr>
                                <td>1,002</td>
                                <td>amet</td>
                                <td>consectetur</td>
                                <td>adipiscing</td>
                                <td>elit</td>
                            </tr>
                            <tr>
                                <td>1,003</td>
                                <td>Integer</td>
                                <td>nec</td>
                                <td>odio</td>
                                <td>Praesent</td>
                            </tr>
                            <tr>
                                <td>1,003</td>
                                <td>libero</td>
                                <td>Sed</td>
                                <td>cursus</td>
                                <td>ante</td>
                            </tr>
                            <tr>
                                <td>1,004</td>
                                <td>dapibus</td>
                                <td>diam</td>
                                <td>Sed</td>
                                <td>nisi</td>
                            </tr>
                            <tr>
                                <td>1,005</td>
                                <td>Nulla</td>
                                <td>quis</td>
                                <td>sem</td>
                                <td>at</td>
                            </tr>
                            <tr>
                                <td>1,006</td>
                                <td>nibh</td>
                                <td>elementum</td>
                                <td>imperdiet</td>
                                <td>Duis</td>
                            </tr>
                            <tr>
                                <td>1,007</td>
                                <td>sagittis</td>
                                <td>ipsum</td>
                                <td>Praesent</td>
                                <td>mauris</td>
                            </tr>
                            <tr>
                                <td>1,008</td>
                                <td>Fusce</td>
                                <td>nec</td>
                                <td>tellus</td>
                                <td>sed</td>
                            </tr>
                            <tr>
                                <td>1,009</td>
                                <td>augue</td>
                                <td>semper</td>
                                <td>porta</td>
                                <td>Mauris</td>
                            </tr>
                            <tr>
                                <td>1,010</td>
                                <td>massa</td>
                                <td>Vestibulum</td>
                                <td>lacinia</td>
                                <td>arcu</td>
                            </tr>
                            <tr>
                                <td>1,011</td>
                                <td>eget</td>
                                <td>nulla</td>
                                <td>Class</td>
                                <td>aptent</td>
                            </tr>
                            <tr>
                                <td>1,012</td>
                                <td>taciti</td>
                                <td>sociosqu</td>
                                <td>ad</td>
                                <td>litora</td>
                            </tr>
                            <tr>
                                <td>1,013</td>
                                <td>torquent</td>
                                <td>per</td>
                                <td>conubia</td>
                                <td>nostra</td>
                            </tr>
                            <tr>
                                <td>1,014</td>
                                <td>per</td>
                                <td>inceptos</td>
                                <td>himenaeos</td>
                                <td>Curabitur</td>
                            </tr>
                            <tr>
                                <td>1,015</td>
                                <td>sodales</td>
                                <td>ligula</td>
                                <td>in</td>
                                <td>libero</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="../assets/dist/js/bootstrap.bundle.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    <script src="{% static 'js/dashboard.js' %}"></script>
</body>

</html>

spaces/templates/spaces/signin.html
{% extends 'spaces/base.html' %}
{% block title %}Connexion{% endblock %}
{% block navbarbrand1 %}<a class="navbar-brand" id="navbarbrand1" href="#">Nouveautés</a>{% endblock navbarbrand1 %}
{% block navlink1 %}<a class="nav-link" href="#" id="navlink1">Forum<span
        class="sr-only">(current)</span></a>{% endblock navlink1 %}
{% block navlink2 %}<a class="nav-link" href="{% url 'spaces:signup' %}"
    id="navlink2">S'enregistrer</a>{% endblock navlink2 %}
{% block navlinkdisabled1 %}<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"
    id="navlinkdisabled1">Se connecter</a>{% endblock navlinkdisabled1 %}
{% block mt51 %}LOGEIQUEMENT{% endblock mt51 %}
{% block lead1 %} Connectez vous !{% endblock lead1 %}
{% block content %}
{% if error %}
<p><strong>Utilisateur inconnu ou mauvais de mot de passe.</strong></p>
{% endif %}
<form method="post" action="{% url 'spaces:signin' %}">
    {% csrf_token %}

    <p>
        {{form.username.label}}
        {{form.username}}
    </p>
    <p>
        {{form.password.label}}
        {{form.password}}
    </p>
    <p>
        {{form.client.label}}
        {{form.client}}


        {{form.landlord.label}}
        {{form.landlord}}
    </p>
    <button type="submit" class="btn btn-primary" name="Connectez vous" value="Connectez vous">Connectez vous</button>
</form>
{% if client_user.is_authenticated %}
Vous êtes connecté client, {{ client_user.username }} !
<P>
    <a href="{% url 'spaces:see_client_profile' client_user.id %}" class="btn btn-lg btn-secondary">Allez à votre compte</a>
</P>
{% elif landlord_user.is_authenticated %}
Vous êtes connecté propietaire, {{ landlord_user.username }}!
<P>
    <a href=" {% url 'spaces:see_landlord_profile' landlord_user.id %}" class="btn btn-lg btn-secondary">Allez à votre compte</a>
</P>
{% endif %}
{% endblock content %}