logeique2/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spaces.urls', namespace='spaces')),
    path('search/', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search, name='search')
]

search/models.py
from django.db import models

# Create your models here.

search/forms.py
from django import forms 

class SearchForm(forms.Form):
    query = forms.CharField(label='', max_length= 200, widget=forms.TextInput(attrs={'id':'query', 'class':'form-control mr-sm-2', 'title':'Rechercher', 'placeholder':'exemple : Marcory...' , 'aria-label':"Search"}))
    query_for_all= forms.BooleanField(label='Tout', required=False, widget=forms.CheckboxInput(attrs={'id':'tout','class':'form-check-input stick' ,'checked':'checked'}))
    query_for_house = forms.BooleanField(label='Maison', required=False, widget=forms.CheckboxInput(attrs={'class':'form-check-input stick', 'onclick':'active()', 'id':'hou'}))
    query_for_client = forms.BooleanField(label='Client', required=False, widget=forms.CheckboxInput(attrs={'class':'form-check-input stick', 'onclick':'active()', 'id':'cli'}))
    query_for_lanlord = forms.BooleanField(label='Propietaire', required=False, widget=forms.CheckboxInput(attrs={'class':'form-check-input stick', 'onclick':'active()', 'id':'lan'}))

search/views.py
from django.shortcuts import render
from .forms import SearchForm
from spaces.models import House , Landlord , Client
from django.db.models import Q
from django.shortcuts import Http404

# Create your views here.

def get_result(value, choice = 1):
    #the case where the user select all checkbox
    clients = []
    landlords = []
    houses = []
    clients_list = []
    landlords_list = []
    houses_list = []
    if (choice == 1):
        try:
            value = int(value)
            houses_list = list(House.objects.filter(
            Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)|Q(house_rent=int(value))|Q(house_deposit=int(value))))
        except ValueError:
            houses_list = list(House.objects.filter(
            Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)))
        if not houses_list:
            houses = houses_list = []
        try:
            value = int(value)
            clients_list = list(Client.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| Q(user__last_name__icontains=value) |
                Q(kind_desire__icontains=value) | Q(rooms_number_desire__icontains=int(value)) | Q(rent_proposal__icontains=int(value))| Q(deposit_proposal__icontains=int(value))))
        except ValueError:
            clients_list = list(Client.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| Q(user__last_name__icontains=value) |Q(kind_desire__icontains=value)))
        if not clients_list:
            clients = clients_list = []
        try:
            value = int(value)
            landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |
            Q(houses__house_area__icontains=value) |Q(houses__house_rent=int(value))|Q(houses__house_deposit=int(value))))
        except ValueError:
           landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| 
            Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |
            Q(houses__house_area__icontains=value) ))
        if not landlords_list:
             landlords = landlords_list = []

     #The case where house checkbox is selected
    elif choice == 2:
        try:
            value = int(value)
            houses_list = list(House.objects.filter(
            Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)|Q(house_rent =int(value)) |Q(house_deposit=int(value))))
        except ValueError:
            houses_list = list(House.objects.filter(
            Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)))
        if not houses_list:
            houses = houses_list = []

    #The case where client checkbox is selected
    elif choice == 3:
        try:
            value = int(value)
            clients_list = list(Client.objects.filter(
                Q(kind_desire__icontains=value) | Q(rooms_number_desire=int(value)) | Q(rent_proposal = int(value))|Q(deposit_proposal = int(value))|
                Q(user__username__icontains = value)|Q(user__first_name__icontains = value)|Q(user__last_name__icontains = value)))
        except ValueError:
            clients_list = list(Client.objects.filter(
                Q(kind_desire__icontains=value) |Q(user__username__icontains = value)|Q(user__first_name__icontains = value)|Q(user__last_name__icontains = value)))
                #We will look for different clients registered which are looking for a particular house or with a particular name
        if not clients_list:
            clients = clients_list = []
            
            
    #The case where landlord checkbox is selected
    elif choice == 4:
        try:
            value = int(value)
            landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| 
            Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |
            Q(houses__house_area__icontains=value) |Q(houses__house_rent=int(value))|Q(houses__house_deposit=int(value))))
        except ValueError:
            landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| 
            Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |Q(houses__house_area__icontains=value) ))
            #We will look for different landlords registered which own a particular house or with a particular name
        if not landlords_list:
            landlords = landlords_list = []
         
            
    if (len(clients_list) > 0 or len(houses_list) > 0 or len(landlords_list)> 0):
            clients = clients_list
            houses = houses_list 
            landlords = landlords_list
    context = {'clients':clients, 'clients_list':clients_list, 'houses':houses, 'houses_list':houses_list,'landlords':landlords,'landlords_list':landlords_list}
    return context


def get_result_two(value , choice1 , choice2):
    clients = []
    landlords = []
    houses = []
    clients_list = []
    landlords_list = []
    houses_list = []
    #The case where house and client checkbox are selected
    if ((choice1 == 2 and  choice2 ==3) or (choice1 == 3 and choice2 == 2)):
        try:
            value = int(value)
            houses_list = list(House.objects.filter(
            Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)|Q(house_rent =int(value)) |Q(house_deposit=int(value))))
        except ValueError:
            houses_list = list(House.objects.filter(Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)))
        if not houses_list:
            houses = houses_list = []
        try:
            value = int(value)
            clients_list = list(Client.objects.filter(
                Q(kind_desire__icontains=value) | Q(rooms_number_desire=int(value)) | Q(rent_proposal = int(value))|Q(deposit_proposal = int(value))|
                Q(user__username__icontains = value)|Q(user__first_name__icontains = value)|Q(user__last_name__icontains = value)))
            #We will look for different clients registered which are looking for a particular house or with a particular name
        except ValueError:
            clients_list = list(Client.objects.filter(
                Q(kind_desire__icontains=value)|Q(user__username__icontains = value)|Q(user__first_name__icontains = value)|Q(user__last_name__icontains = value)))
        if not clients_list:
            clients = clients_list = []
            
            
    #The case where house and landlord checkbox are selected
    if((choice1 == 2 and choice2 == 4) or (choice1 == 4 and choice2 == 2)):
        try:
            value = int(value)
            houses_list = list(House.objects.filter(Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)|Q(house_rent =int(value)) |Q(house_deposit=int(value))))
        except ValueError:
            houses_list = list(House.objects.filter(Q(house_township__icontains=value) | Q(house_area__icontains=value) |Q(house_kind__icontains=value)))
        if not houses_list:
            houses = houses_list = []
        try:
            value = int(value)
            landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| 
            Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |
            Q(houses__house_area__icontains=value) |Q(houses__house_rent=int(value))|Q(houses__house_deposit=int(value))))
            #We will look for different landlords registered which own a particular house or with a particular name
        except ValueError:
            landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| 
            Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |
            Q(houses__house_area__icontains=value)))
        if not landlords_list:
            landlords = landlords_list = []
    #The case where client and landlord checkbox are selected
    if((choice1 == 3 and choice2 == 4) or (choice1 == 4 and choice2 == 3)):
        try:
            value = int(value)
            clients_list = list(Client.objects.filter(
                Q(kind_desire__icontains=value) | Q(rooms_number_desire=int(value)) | Q(rent_proposal = int(value))|Q(deposit_proposal = int(value))|
                Q(user__username__icontains = value)|Q(user__first_name__icontains = value)|Q(user__last_name__icontains = value)))
                #We will look for different clients registered which are looking for a particular house or with a particular name
        except ValueError:
            clients_list = list(Client.objects.filter(
                Q(kind_desire__icontains=value)|Q(user__username__icontains = value)|Q(user__first_name__icontains = value)|Q(user__last_name__icontains = value)))
        if not clients_list:
            clients = clients_list = []
    #The case where landlord checkbox is selected
        try:
            value = int(value)
            landlords_list = list(Landlord.objects.filter(Q(user__username__icontains = value)| Q(user__first_name__icontains=value)| 
                Q(user__last_name__icontains=value)| Q(houses__house_township__icontains=value) |
                Q(houses__house_area__icontains=value) |Q(houses__house_rent=int(value))|Q(houses__house_deposit=int(value))))

search/templates/search/search.html
<form method='GET' action="{% url 'search:search' %}">
    <p>
        {{form.query.label}}
        {{form.query}}
    </p>
    <div class="form-check form-check-inline">
        {{form.query_for_all.label}}
        {{form.query_for_all}}

        {{form.query_for_house.label}}
        {{form.query_for_house}}

        {{form.query_for_client.label}}
        {{form.query_for_client}}

        {{form.query_for_lanlord.label}}
        {{form.query_for_lanlord}}
</div>

</form>

search/templates/search/search_result.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" 
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
    <div>
        {% if context.clients %}
        <h3>Clients interessés par ce genre de maisons</h3>
            {% for client in context.clients %}
                <p>{{client.user.username}}</p>
            {% endfor %}
        {% endif %}
        </div>
        
        <div>
        {% if context.landlords %}
        <h3>Proprietaires concernés</h3>
            {% for landlord in context.landlords %}
            <div>
                {{landlord.user.username}}
                {{landlord.contact}}
            </div>
            {% endfor %}
        {% endif %}
        </div>
        
        <div>
        {% if context.houses %}
        <h3>Maisons concernés</h3>
        {% for house in context.houses %}
        <div class="row row-cols-1 row-cols-md-2">
            <div class="col mb-4">
                <div class="card">
                    <img src="{{house.house_image.url}}" class="card-img-top" alt="pas d'image">
                    <div class="card-body">
                        <h5 class="card-title">TYpe: {{house.house_kind}}</h5>
                        <p class="card-text">COmmune: {{house.house_township}}</p>
                    </div>
                </div>
            </div>
        </div>
              
        <!--
            <div>
                
               QUartier: {{house.house_area}} 
                
               LOyer: {{house.house_rent}}
               CAution: {{house.house_deposit}}
               NOmbre de pieces: {{house.house_rooms_number}}
               {% if house.house_to_sell %}
                    maison à vendre
               {% else %}
                    pas à vendre
               {% endif %}
               {% if house.house_available %}
                    Maison disponible
               {% else %}
                    Maison occupée
                {% endif %}
            </div>
            {% endfor %}
            {% endif %}
        
        {% if not context.clients and not context.landlords and not context.houses %}
            <h1> Aucun resultat</h1>
        {% endif %}
        </div>
        --> 
</body>
</html>